In [5]:
import pandas as pd

## Carregamento dos dados

In [342]:
data = pd.read_csv('./dataset/data_cancer2.csv',sep=',')
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [307]:
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

## Tratando dados missing (nulos)

In [8]:
data.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

não temos dados nulos no dataset, sendo assim, podemos avançar para próxima etapa

## Tratamento de variáveis 

Transformando variáveis categoricas nominais em ordinais

- diagnosis (alvo) </br>
M - 1
B - 0

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
data2 = data.copy()

In [11]:
data2.iloc[:,1] = LabelEncoder().fit_transform(data2.iloc[:,1])

Analisando correlação das variáveis através da correlação de Pearson

In [12]:
correlacao = data2.corr(method='pearson')['diagnosis'].sort_values(ascending=False)
correlacao

diagnosis                  1.000000
concave points_worst       0.793566
perimeter_worst            0.782914
concave points_mean        0.776614
radius_worst               0.776454
perimeter_mean             0.742636
area_worst                 0.733825
radius_mean                0.730029
area_mean                  0.708984
concavity_mean             0.696360
concavity_worst            0.659610
compactness_mean           0.596534
compactness_worst          0.590998
radius_se                  0.567134
perimeter_se               0.556141
area_se                    0.548236
texture_worst              0.456903
smoothness_worst           0.421465
symmetry_worst             0.416294
texture_mean               0.415185
concave points_se          0.408042
smoothness_mean            0.358560
symmetry_mean              0.330499
fractal_dimension_worst    0.323872
compactness_se             0.292999
concavity_se               0.253730
fractal_dimension_se       0.077972
id                         0

## Previsores e alvo
- alvo: variável com transformação categorica ordinal
- previsores: variável previsores sem nenhum pré processamento
- previsores_esc: variável previsores com escalonamento (padronização)
- previsores_decompose: variável previsores com redução de dimensionalidade --> n_components=10,random_state=0
- previsores_escDecompose: variável previsores_decompose com escalonamento (padronização)

In [13]:
from sklearn.preprocessing import StandardScaler

Relacionando variáveis que seram utilizadas como previsores e alvo

In [14]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [155]:
previsores = data2.iloc[:,[2, 3, 4, 5, 7, 8, 9, 12, 14, 15, 19, 22, 23, 24, 25, 26, 27, 28, 29, 30]].values
previsores

array([[ 17.99  ,  10.38  , 122.8   , ...,   0.7119,   0.2654,   0.4601],
       [ 20.57  ,  17.77  , 132.9   , ...,   0.2416,   0.186 ,   0.275 ],
       [ 19.69  ,  21.25  , 130.    , ...,   0.4504,   0.243 ,   0.3613],
       ...,
       [ 16.6   ,  28.08  , 108.3   , ...,   0.3403,   0.1418,   0.2218],
       [ 20.6   ,  29.33  , 140.1   , ...,   0.9387,   0.265 ,   0.4087],
       [  7.76  ,  24.54  ,  47.92  , ...,   0.    ,   0.    ,   0.2871]])

reduzindo dimensionalidade

In [16]:
from sklearn.decomposition import PCA

In [156]:
reducao = PCA(n_components=10,random_state=0)
previsores_decompose = reducao.fit_transform(previsores)
previsores_decompose

array([[ 1.16014256e+03, -2.93917487e+02,  4.85804354e+01, ...,
        -2.12566452e-01, -7.33987643e-01, -4.00548771e-01],
       [ 1.26912241e+03,  1.56303314e+01, -3.53925292e+01, ...,
         2.12712802e-01,  4.83528113e-01,  8.67153251e-02],
       [ 9.95793863e+02,  3.91568738e+01, -1.70737748e+00, ...,
        -1.35483607e-01,  1.73349430e-01,  3.09740189e-01],
       ...,
       [ 3.14501748e+02,  4.75535701e+01, -1.04419383e+01, ...,
        -2.72400694e-01,  9.63987910e-02, -7.56224407e-02],
       [ 1.12485814e+03,  3.41290755e+01, -1.97454491e+01, ...,
        -6.95206466e-01, -3.64298031e-01,  2.07993946e-01],
       [-7.71527609e+02, -8.86431751e+01,  2.38881215e+01, ...,
         1.81026586e-01,  4.15394565e-01,  1.84627832e-01]])

In [157]:
previsores_esc = StandardScaler().fit_transform(previsores_decompose)
previsores_esc

array([[ 1.74304334, -3.44069168,  1.83280721, ..., -0.40868446,
        -1.86468095, -2.21926804],
       [ 1.90677893,  0.18297364, -1.33526351, ...,  0.40896583,
         1.22839352,  0.48045223],
       [ 1.49611947,  0.45838283, -0.06441469, ..., -0.26048346,
         0.44039077,  1.71613684],
       ...,
       [ 0.47251967,  0.55667723, -0.39394583, ..., -0.52372295,
         0.2448992 , -0.41899134],
       [ 1.69003066,  0.39952582, -0.74494189, ..., -1.33661768,
        -0.92549188,  1.15240477],
       [-1.15917312, -1.03768523,  0.90123361, ...,  0.34804529,
         1.0553016 ,  1.02294321]])

In [158]:
previsores_escDecompose = StandardScaler().fit_transform(previsores_esc)
previsores_escDecompose

array([[ 1.74304334, -3.44069168,  1.83280721, ..., -0.40868446,
        -1.86468095, -2.21926804],
       [ 1.90677893,  0.18297364, -1.33526351, ...,  0.40896583,
         1.22839352,  0.48045223],
       [ 1.49611947,  0.45838283, -0.06441469, ..., -0.26048346,
         0.44039077,  1.71613684],
       ...,
       [ 0.47251967,  0.55667723, -0.39394583, ..., -0.52372295,
         0.2448992 , -0.41899134],
       [ 1.69003066,  0.39952582, -0.74494189, ..., -1.33661768,
        -0.92549188,  1.15240477],
       [-1.15917312, -1.03768523,  0.90123361, ...,  0.34804529,
         1.0553016 ,  1.02294321]])

In [159]:
alvo = data2.iloc[:,1].values
alvo = alvo.astype(int)
alvo

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

## Definindo dados de treino e dados de teste

In [21]:
from sklearn.model_selection import train_test_split  

In [22]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores_decompose,alvo,test_size=0.3,shuffle=True,random_state=3)

## Nayve Bayes

In [23]:
from sklearn.naive_bayes import GaussianNB

In [24]:
naive = GaussianNB()
naive.fit(x_treino,y_treino)

GaussianNB()

### Dados de teste

In [25]:
previsoes_teste = naive.predict(x_teste)
previsoes_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

In [26]:
y_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

Métricas de avaliação (Teste)

In [28]:
accuracy_score(previsoes_teste,y_teste)

0.9122807017543859

In [29]:
confusion_matrix(previsoes_teste,y_teste)

array([[101,   7],
       [  8,  55]], dtype=int64)

In [30]:
print(classification_report(previsoes_teste,y_teste))

              precision    recall  f1-score   support

           0       0.93      0.94      0.93       108
           1       0.89      0.87      0.88        63

    accuracy                           0.91       171
   macro avg       0.91      0.90      0.91       171
weighted avg       0.91      0.91      0.91       171



### Dados de treino

In [31]:
previsoes_treino = naive.predict(x_treino)
previsoes_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,

In [32]:
y_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,

Métricas de avaliação (Treino)

In [33]:
accuracy_score(previsoes_treino,y_treino)

0.8869346733668342

In [34]:
confusion_matrix(previsoes_treino,y_treino)

array([[232,  29],
       [ 16, 121]], dtype=int64)

In [35]:
print(classification_report(previsoes_treino,y_treino))

              precision    recall  f1-score   support

           0       0.94      0.89      0.91       261
           1       0.81      0.88      0.84       137

    accuracy                           0.89       398
   macro avg       0.87      0.89      0.88       398
weighted avg       0.89      0.89      0.89       398



### Validação Cruzada

In [36]:
from sklearn.model_selection import KFold, cross_val_score

In [37]:
modelo = GaussianNB()

In [38]:
kfold = KFold(n_splits=30,shuffle=True,random_state=3)

In [39]:
resultado = cross_val_score(modelo,previsores_decompose,alvo,cv=kfold)
acuracia_mean = resultado.mean()
acuracia_mean

0.8910331384015593

## Maquina de vetores suporte (svm)

In [40]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

In [41]:
svm = SVC(C=1,gamma='scale',kernel='rbf',random_state=5)
svm.fit(x_treino,y_treino)

SVC(C=1, random_state=5)

### Otimizando hiperparâmetros (gridsearch)

In [42]:
parametros_grid = dict(
    C=[1,2,3],
    gamma=['auto','scale'],
    kernel=['linear', 'rbf']
)

In [43]:
# gridSearch = GridSearchCV(svm,param_grid=parametros_grid,scoring='accuracy',cv=5)
# gridSearch.fit(x_treino,y_treino)

In [44]:
# gridSearch.best_params_

In [45]:
# tableParams = pd.DataFrame(gridSearch.cv_results_)
# tableParams.head(4).sort_values(by='rank_test_score',ascending=True).iloc[:,[4,5,6,7,13,15]]

### Dados de Teste

In [46]:
previsoes_teste = svm.predict(x_teste)
previsoes_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

In [47]:
y_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

métricas de avaliação (Teste)

In [48]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [49]:
accuracy_score(previsoes_teste,y_teste)

0.9239766081871345

In [50]:
confusion_matrix(previsoes_teste,y_teste)

array([[106,  10],
       [  3,  52]], dtype=int64)

In [51]:
print(classification_report(previsoes_teste,y_teste))

              precision    recall  f1-score   support

           0       0.97      0.91      0.94       116
           1       0.84      0.95      0.89        55

    accuracy                           0.92       171
   macro avg       0.91      0.93      0.92       171
weighted avg       0.93      0.92      0.93       171



### Dados de treino

In [52]:
previsoes_treino = svm.predict(x_treino)
previsoes_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,

In [53]:
y_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,

Métricas de avaliação (Treino)

In [54]:
accuracy_score(previsoes_treino,y_treino)

0.9271356783919598

In [55]:
confusion_matrix(previsoes_treino,y_treino)

array([[242,  23],
       [  6, 127]], dtype=int64)

In [56]:
print(classification_report(previsoes_treino,y_treino))

              precision    recall  f1-score   support

           0       0.98      0.91      0.94       265
           1       0.85      0.95      0.90       133

    accuracy                           0.93       398
   macro avg       0.91      0.93      0.92       398
weighted avg       0.93      0.93      0.93       398



### Validação Cruzada

In [57]:
modelo = SVC(C=1,gamma='scale',kernel='rbf')

In [58]:
kfold = KFold(n_splits=60,shuffle=True,random_state=5)

In [59]:
resultado = cross_val_score(modelo,previsores_decompose,alvo,cv=kfold)
acuracia_mean = resultado.mean()
acuracia_mean

0.9205555555555556

## KNN (Aprendizagem baseado em instâncias)

In [160]:
from sklearn.neighbors import KNeighborsClassifier

In [161]:
knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2,weights='uniform')
knn.fit(x_treino,y_treino)

KNeighborsClassifier()

### Otimizando Hiperparâmetros (GridSearch)

In [162]:
parametros_grid = dict(
    n_neighbors=[1,2,3,4,5],
    metric=['minkowski','euclidean','manhattan'],
    p=[1,2],
    weights=['uniform', 'distance']
)

In [163]:
gridSearch = GridSearchCV(knn,param_grid=parametros_grid,scoring='accuracy',cv=5)
gridSearch.fit(x_treino,y_treino)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [1, 2, 3, 4, 5], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [164]:
tableParams = pd.DataFrame(gridSearch.cv_results_)
tableParams.head(4).sort_values(by='rank_test_score',ascending=True)
print(tableParams.iloc[3:4,8])


3    {'metric': 'minkowski', 'n_neighbors': 1, 'p':...
Name: params, dtype: object


### Dados de teste

In [165]:
previsoes_teste = knn.predict(x_teste)
previsoes_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

In [166]:
y_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

Métricas de avaliação (Teste)

In [167]:
accuracy_score(previsoes_teste,y_teste)

0.9239766081871345

In [168]:
confusion_matrix(previsoes_teste,y_teste)

array([[104,   8],
       [  5,  54]], dtype=int64)

In [169]:
print(classification_report(previsoes_teste,y_teste))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94       112
           1       0.87      0.92      0.89        59

    accuracy                           0.92       171
   macro avg       0.91      0.92      0.92       171
weighted avg       0.93      0.92      0.92       171



### Dados de Treino

In [170]:
previsoes_treino = knn.predict(x_treino)
previsoes_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,

In [171]:
y_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,

Métricas de avaliação (Treino)

In [172]:
accuracy_score(previsoes_treino,y_treino)

0.9422110552763819

In [173]:
confusion_matrix(previsoes_treino,y_treino)

array([[241,  16],
       [  7, 134]], dtype=int64)

In [174]:
print(classification_report(previsoes_treino,y_treino))

              precision    recall  f1-score   support

           0       0.97      0.94      0.95       257
           1       0.89      0.95      0.92       141

    accuracy                           0.94       398
   macro avg       0.93      0.94      0.94       398
weighted avg       0.94      0.94      0.94       398



### Validação Cruzada

In [175]:
modelo = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2,weights='uniform')

In [176]:
kfold = KFold(n_splits=60,shuffle=True,random_state=5)

In [177]:
resultado = cross_val_score(modelo,previsores,alvo,cv=kfold)
acuracia_mean = resultado.mean()
acuracia_mean

0.9322222222222222

In [178]:
from sklearn.linear_model import LogisticRegression

In [179]:
rl = LogisticRegression()

otimizando com gridSearch

In [180]:
parametros_grid = dict(
    penalty=['l1', 'l2', 'elasticnet'],
    C = [number for number in range(1,6,1)],
    solver=['lbfgs', 'liblinear', 'newton-cg'],
    max_iter=[100]
)

In [181]:
gridSearch = GridSearchCV(rl,param_grid=parametros_grid,scoring='accuracy',cv=5)
gridSearch.fit(x_treino,y_treino)

c:\Users\Gustavo PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Gustavo PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-le

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5], 'max_iter': [100],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg']},
             scoring='accuracy')

In [182]:
tableParams = pd.DataFrame(gridSearch.cv_results_)
tableParams.head(4).sort_values(by='rank_test_score',ascending=
                                True)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
1       0.001393      0.001187         0.000402        0.000803        1   
3       0.016518      0.016990         0.000402        0.000804        1   
0       0.000401      0.000803         0.000000        0.000000        1   
2       0.000000      0.000000         0.000000        0.000000        1   

   param_max_iter param_penalty param_solver  \
1             100            l1    liblinear   
3             100            l2        lbfgs   
0             100            l1        lbfgs   
2             100            l1    newton-cg   

                                              params  split0_test_score  \
1  {'C': 1, 'max_iter': 100, 'penalty': 'l1', 'so...             0.9875   
3  {'C': 1, 'max_iter': 100, 'penalty': 'l2', 'so...             0.9750   
0  {'C': 1, 'max_iter': 100, 'penalty': 'l1', 'so...                NaN   
2  {'C': 1, 'max_iter': 100, 'penalty': 'l1', 'so...                NaN   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
1             0.9375               0.95           0.924051           0.936709   
3             0.9250               0.95           0.911392           0.936709   
0                NaN                NaN                NaN                NaN   
2                NaN                NaN                NaN                NaN   

   mean_test_score  std_test_score  rank_test_score  
1         0.947152        0.021781                9  
3         0.939620        0.021811               20  
0              NaN             NaN               21  
2              NaN             NaN               21

## Árvore de decisão

In [83]:
from sklearn.tree import DecisionTreeClassifier

In [84]:
arvoreDecisao = DecisionTreeClassifier(criterion='entropy',max_depth=2,splitter='best',random_state=0)
arvoreDecisao.fit(x_treino,y_treino)

DecisionTreeClassifier(criterion='entropy', max_depth=2, random_state=0)

otimização com gridSearch

In [85]:
parametros_grid = dict(
    criterion=['gini', 'entropy'],
    splitter=['best', 'random'],
    max_depth=[number for number in range(1,5,1)],
    max_features=['auto', 'sqrt', 'log2']
)

gridSearch = GridSearchCV(arvoreDecisao,param_grid=parametros_grid,scoring='accuracy',cv=5)
gridSearch.fit(x_treino,y_treino)

c:\Users\Gustavo PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
80 fits failed out of a total of 240.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
80 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Gustavo PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Gustavo PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "c:\Users\Gustavo PC\AppData\Local\Programs\Python\Python311\Lib\site-pac

GridSearchCV(cv=5,
             estimator=DecisionTreeClassifier(criterion='entropy', max_depth=2,
                                              random_state=0),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='accuracy')

In [86]:
tableParams = pd.DataFrame(gridSearch.cv_results_)
tableParams.head(5).sort_values(by='rank_test_score',ascending=True)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
3       0.000350      0.000699         0.002086        0.002104   
2       0.003117      0.002744         0.003510        0.005087   
4       0.000000      0.000000         0.002155        0.003259   
0       0.000402      0.000804         0.000000        0.000000   
1       0.000401      0.000803         0.000000        0.000000   

  param_criterion  param_max_depth param_max_features param_splitter  \
3            gini                1               sqrt         random   
2            gini                1               sqrt           best   
4            gini                1               log2           best   
0            gini                1               auto           best   
1            gini                1               auto         random   

                                              params  split0_test_score  \
3  {'criterion': 'gini', 'max_depth': 1, 'max_fea...             0.9125   
2  {'criterion': 'gini', 'max_depth': 1, 'max_fea...             0.6750   
4  {'criterion': 'gini', 'max_depth': 1, 'max_fea...             0.6750   
0  {'criterion': 'gini', 'max_depth': 1, 'max_fea...                NaN   
1  {'criterion': 'gini', 'max_depth': 1, 'max_fea...                NaN   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
3              0.775              0.825           0.721519           0.759494   
2              0.725              0.700           0.759494           0.696203   
4              0.725              0.700           0.759494           0.696203   
0                NaN                NaN                NaN                NaN   
1                NaN                NaN                NaN                NaN   

   mean_test_score  std_test_score  rank_test_score  
3         0.798703        0.065875               25  
2         0.711139        0.028926               29  
4         0.711139        0.028926               29  
0              NaN             NaN               33  
1              NaN             NaN               33

### Dados de Teste

In [87]:
previsoes_teste = arvoreDecisao.predict(x_teste)
previsoes_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0])

In [88]:
y_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

Métricas de avaliação (Teste)

In [89]:
accuracy_score(previsoes_teste,y_teste)

0.9122807017543859

In [90]:
confusion_matrix(previsoes_teste,y_teste)

array([[98,  4],
       [11, 58]], dtype=int64)

In [91]:
print(classification_report(previsoes_teste,y_teste))

              precision    recall  f1-score   support

           0       0.90      0.96      0.93       102
           1       0.94      0.84      0.89        69

    accuracy                           0.91       171
   macro avg       0.92      0.90      0.91       171
weighted avg       0.91      0.91      0.91       171



### Dados de treino

In [92]:
previsoes_treino = arvoreDecisao.predict(x_treino)
previsoes_treino

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,

In [93]:
y_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,

Métricas de avaliação (Treino)

In [94]:
accuracy_score(previsoes_treino,y_treino)

0.9321608040201005

### Validação Cruzada

In [95]:
modelo = DecisionTreeClassifier(criterion='entropy',max_depth=2,splitter='best',random_state=4)

In [96]:
kfold = KFold(n_splits=60,shuffle=True,random_state=5)

In [97]:
resultado = cross_val_score(modelo,previsores_decompose,alvo,cv=kfold)
acuracia_mean = resultado.mean()
acuracia_mean

0.9203703703703703

## Random Florest (floresta aleatória)

In [98]:
from sklearn.ensemble import RandomForestClassifier

In [99]:
randomFlorest = RandomForestClassifier(criterion='gini',n_estimators=200,max_depth=2,random_state=0)
randomFlorest.fit(x_treino,y_treino)

RandomForestClassifier(max_depth=2, n_estimators=200, random_state=0)

### Otimizando hiperparâmetros (GridSearch)

In [100]:
parametros_grid = dict(
    criterion=['gini', 'entropy'],
    n_estimators=[100,200,300],
    max_depth=[1,2,3,4],
    random_state=[0]
)

gridSearch = GridSearchCV(randomFlorest,param_grid=parametros_grid,scoring='accuracy',cv=5)
gridSearch.fit(x_treino,y_treino)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(max_depth=2, n_estimators=200,
                                              random_state=0),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4],
                         'n_estimators': [100, 200, 300], 'random_state': [0]},
             scoring='accuracy')

In [101]:
tableParams = pd.DataFrame(gridSearch.cv_results_)
tableParams.head(5).sort_values(by='rank_test_score',ascending=True)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
3       0.136196      0.020059         0.008195        0.007148   
4       0.277625      0.040848         0.006312        0.007730   
2       0.455880      0.016158         0.010528        0.013344   
1       0.296345      0.034495         0.003120        0.003821   
0       0.153167      0.025716         0.004310        0.005947   

  param_criterion  param_max_depth  param_n_estimators  param_random_state  \
3            gini                2                 100                   0   
4            gini                2                 200                   0   
2            gini                1                 300                   0   
1            gini                1                 200                   0   
0            gini                1                 100                   0   

                                              params  split0_test_score  \
3  {'criterion': 'gini', 'max_depth': 2, 'n_estim...             0.9625   
4  {'criterion': 'gini', 'max_depth': 2, 'n_estim...             0.9625   
2  {'criterion': 'gini', 'max_depth': 1, 'n_estim...             0.9250   
1  {'criterion': 'gini', 'max_depth': 1, 'n_estim...             0.9250   
0  {'criterion': 'gini', 'max_depth': 1, 'n_estim...             0.9125   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
3             0.8875             0.9500           0.886076           0.936709   
4             0.8875             0.9500           0.886076           0.936709   
2             0.8375             0.9000           0.860759           0.898734   
1             0.8375             0.8875           0.835443           0.898734   
0             0.8250             0.8750           0.797468           0.898734   

   mean_test_score  std_test_score  rank_test_score  
3         0.924557        0.031902               13  
4         0.924557        0.031902               13  
2         0.884399        0.031163               19  
1         0.876835        0.035139               22  
0         0.861741        0.043822               24

### Dados de teste

In [102]:
previsoes_teste = randomFlorest.predict(x_teste)
previsoes_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

In [103]:
y_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

Métricas de avaliação (Teste)

In [104]:
accuracy_score(previsoes_teste,y_teste)

0.9181286549707602

In [105]:
confusion_matrix(previsoes_teste,y_teste)

array([[105,  10],
       [  4,  52]], dtype=int64)

In [106]:
print(classification_report(previsoes_teste,y_teste))

              precision    recall  f1-score   support

           0       0.96      0.91      0.94       115
           1       0.84      0.93      0.88        56

    accuracy                           0.92       171
   macro avg       0.90      0.92      0.91       171
weighted avg       0.92      0.92      0.92       171



### Dados de Treino

In [107]:
previsoes_treino = randomFlorest.predict(x_treino)
previsoes_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,

In [108]:
y_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,

Métricas de avaliação (Treino)

In [109]:
accuracy_score(previsoes_treino,y_treino)

0.9447236180904522

In [110]:
confusion_matrix(previsoes_treino,y_treino)

array([[244,  18],
       [  4, 132]], dtype=int64)

In [111]:
print(classification_report(previsoes_treino,y_treino))

              precision    recall  f1-score   support

           0       0.98      0.93      0.96       262
           1       0.88      0.97      0.92       136

    accuracy                           0.94       398
   macro avg       0.93      0.95      0.94       398
weighted avg       0.95      0.94      0.95       398



### Validação Cruzada

In [112]:
modelo = RandomForestClassifier(criterion='gini',n_estimators=200,max_depth=2,random_state=0)

In [113]:
kfold = KFold(n_splits=60,shuffle=True,random_state=5)

In [114]:
resultado = cross_val_score(modelo,previsores_decompose,alvo,cv=kfold)
acuracia_mean = resultado.mean()
acuracia_mean

0.9261111111111112

## XgBoost

In [115]:
from xgboost import XGBClassifier

In [116]:
xgb = XGBClassifier(learning_rate=0.01,n_estimators=300,objective='binary:logistic',max_depth=2,random_state=0)
xgb.fit(x_treino,y_treino)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, random_state=0, ...)

### Dados de teste

In [117]:
previsoes_teste = xgb.predict(x_teste)
previsoes_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

In [118]:
y_teste

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0])

Métricas de avaliação (Teste)

In [119]:
accuracy_score(previsoes_teste,y_teste)

0.9239766081871345

In [120]:
confusion_matrix(previsoes_teste,y_teste)

array([[104,   8],
       [  5,  54]], dtype=int64)

In [121]:
print(classification_report(previsoes_teste,y_teste))

              precision    recall  f1-score   support

           0       0.95      0.93      0.94       112
           1       0.87      0.92      0.89        59

    accuracy                           0.92       171
   macro avg       0.91      0.92      0.92       171
weighted avg       0.93      0.92      0.92       171



### Dados de Treino

In [122]:
previsoes_treino = xgb.predict(x_treino)
previsoes_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,

In [123]:
y_treino

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,

Métricas de avaliação (Treino)

In [124]:
accuracy_score(previsoes_treino,y_treino)

0.9623115577889447

In [125]:
confusion_matrix(previsoes_treino,y_treino)

array([[243,  10],
       [  5, 140]], dtype=int64)

In [126]:
print(classification_report(previsoes_treino,y_treino))

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       253
           1       0.93      0.97      0.95       145

    accuracy                           0.96       398
   macro avg       0.96      0.96      0.96       398
weighted avg       0.96      0.96      0.96       398



### Validação Cruzada

In [127]:
modelo = XGBClassifier(learning_rate=0.01,n_estimators=300,objective='binary:logistic',max_depth=2,random_state=0)

In [128]:
kfold = KFold(n_splits=60,shuffle=True,random_state=5)

In [129]:
resultado = cross_val_score(modelo,previsores_decompose,alvo,cv=kfold)

print(resultado.mean())

0.9405555555555556


## Salvando dados

In [130]:
import numpy as np

salvando arquivo de previsores

In [131]:
np.savetxt(f'previsores.csv',previsores,delimiter=',')

salvando arquivo de previsores_decompose

In [132]:
np.savetxt(f'previsores_decompose.csv',previsores_decompose,delimiter=',')

salvando arquivo de alvo

In [133]:
np.savetxt(f'alvo.csv',alvo,delimiter=',')

In [200]:
previsores = pd.read_csv('./previsores.csv',sep=',',header=None)
previsores

0       1        2       3       4       5      6       7        8   \
0    0.2654  184.60  0.14710  25.380  122.80  2019.0  17.99  1001.0  0.30010   
1    0.1860  158.80  0.07017  24.990  132.90  1956.0  20.57  1326.0  0.08690   
2    0.2430  152.50  0.12790  23.570  130.00  1709.0  19.69  1203.0  0.19740   
3    0.2575   98.87  0.10520  14.910   77.58   567.7  11.42   386.1  0.24140   
4    0.1625  152.20  0.10430  22.540  135.10  1575.0  20.29  1297.0  0.19800   
..      ...     ...      ...     ...     ...     ...    ...     ...      ...   
564  0.2216  166.10  0.13890  25.450  142.00  2027.0  21.56  1479.0  0.24390   
565  0.1628  155.00  0.09791  23.690  131.20  1731.0  20.13  1261.0  0.14400   
566  0.1418  126.70  0.05302  18.980  108.30  1124.0  16.60   858.1  0.09251   
567  0.2650  184.60  0.15200  25.740  140.10  1821.0  20.60  1265.0  0.35140   
568  0.0000   59.16  0.00000   9.456   47.92   268.6   7.76   181.0  0.00000   

         9        10       11     12      13      14     15       16      17  \
0    0.7119  0.27760  0.66560  8.589  153.40  1.0950  17.33  0.16220  0.4601   
1    0.2416  0.07864  0.18660  3.398   74.08  0.5435  23.41  0.12380  0.2750   
2    0.4504  0.15990  0.42450  4.585   94.03  0.7456  25.53  0.14440  0.3613   
3    0.6869  0.28390  0.86630  3.445   27.23  0.4956  26.50  0.20980  0.6638   
4    0.4000  0.13280  0.20500  5.438   94.44  0.7572  16.67  0.13740  0.2364   
..      ...      ...      ...    ...     ...     ...    ...      ...     ...   
564  0.4107  0.11590  0.21130  7.673  158.70  1.1760  26.40  0.14100  0.2060   
565  0.3215  0.10340  0.19220  5.203   99.04  0.7655  38.25  0.11660  0.2572   
566  0.3403  0.10230  0.30940  3.425   48.55  0.4564  34.12  0.11390  0.2218   
567  0.9387  0.27700  0.86810  5.772   86.22  0.7260  39.42  0.16500  0.4087   
568  0.0000  0.04362  0.06444  2.548   19.15  0.3857  30.37  0.08996  0.2871   

        18       19  
0    10.38  0.01587  
1    17.77  0.01340  
2    21.25  0.02058  
3    20.38  0.01867  
4    14.34  0.01885  
..     ...      ...  
564  22.39  0.02454  
565  28.25  0.01678  
566  28.08  0.01557  
567  29.33  0.01664  
568  24.54  0.00000  

[569 rows x 20 columns]

In [198]:
previsores_decompose = pd.read_csv('./previsores_decompose.csv',sep=',',header=None)
previsores_decompose 

0           1          2          3          4         5  \
0    1160.142555 -293.917487  48.580435   8.797310 -31.978694 -1.274441   
1    1269.122415   15.630331 -35.392529 -17.871895   4.288568  0.225014   
2     995.793863   39.156874  -1.707377  -4.193208   0.467616  2.657525   
3    -407.180809  -67.380289   8.673331  11.781631  -7.078798 -1.296614   
4     930.341154  189.340884   1.377826  -8.473836  -7.628205 -1.021804   
..           ...         ...        ...        ...        ...       ...   
564  1414.126689  110.222442  40.066179  -6.571433   5.092455  0.398808   
565  1045.018938   77.057133   0.028436   4.697172  12.392920  0.050741   
566   314.501748   47.553570 -10.441938   9.761983   6.193879  0.880230   
567  1124.858141   34.129075 -19.745449  23.662096  -3.514665 -4.086108   
568  -771.527609  -88.643175  23.888121  -2.581790  14.719045 -4.409319   

            6         7         8         9  
0   -0.890982 -0.212566 -0.733988 -0.400549  
1    0.051085  0.212713  0.483528  0.086715  
2    0.756082 -0.135484  0.173349  0.309740  
3    1.264437 -0.048028  0.335319  0.936535  
4    0.343227  0.307388 -0.041251  0.058535  
..        ...       ...       ...       ...  
564  0.774951  0.161068  0.447178  0.197512  
565 -0.403916  0.137006  0.458417 -0.084025  
566  2.131728 -0.272401  0.096399 -0.075622  
567  1.723123 -0.695206 -0.364298  0.207994  
568  2.799894  0.181027  0.415395  0.184628  

[569 rows x 10 columns]

In [199]:
alvo = pd.read_csv('./alvo.csv',sep=',',header=None)
alvo

0
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
..   ...
564  1.0
565  1.0
566  1.0
567  1.0
568  0.0

[569 rows x 1 columns]

In [202]:
# Definindo previsores e alvo de deploy
previsores_deploy = previsores.values
previsores_decompose_deploy = previsores_decompose.values
alvo_deploy = alvo.values

Configuração dos algoritmos 

In [203]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2,weights='uniform')

from xgboost import XGBClassifier
xgb = XGBClassifier(learning_rate=0.01,n_estimators=300,objective='binary:logistic',max_depth=2,random_state=0)

## Simulando testes

### Testes algoritmo KNN

O algoritmo KNN teve um melhor desempenho com os 'previsores', sendo assim, faremos testes utilizando dados randômicos.

In [239]:
# Teste1 (valores Randômicos)
paciente1 = [
    14.23, 12.45, 97.52, 645, 0.132, 0.0543, 0.0298, 0.1784, 1.512, 13.24,
    0.00732, 13.76, 22.53, 105.78, 590.3, 0.1246, 0.2651, 0.2023, 0.07954, 0.3048
]
paciente1 = np.asarray(paciente1).reshape(1,-1)

# Teste2 (valores do dataset) - id: 866458/diagnosis esperado: B
paciente2 = [
    15.1, 16.39, 99.58, 674.5, 0.1807, 0.1138, 0.08534, 0.4309, 2.796, 39.84,
    0.02258, 16.11, 18.33, 105.9, 762.6, 0.1386, 0.2883, 0.196, 0.1423, 0.259
]

paciente2 = np.asarray(paciente2).reshape(1,-1)


In [332]:
def diagnostico(result):
    if result == 1:
        print('Câncer está com diagnostico Maligno')
    else:
        print('Câncer está com diagnostico Benigno')

In [217]:
# Treinando algoritmo
knn.fit(previsores_deploy,alvo_deploy)

c:\Users\Gustavo PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [249]:
resultado1 = knn.predict(paciente1)
diagnostico(resultado1)

Câncer está com diagnostico Benigno


In [250]:
resultado2 = knn.predict(paciente2)
diagnostico(resultado2)

Câncer está com diagnostico Benigno


### Testes algoritmo XgBoost

O algoritmo XgBoost teve um melhor desempenho com os 'previsores_decompose', sendo assim, faremos testes utilizando dados reais e randômicos.

In [253]:
colunas_originais = previsores.columns  # Obter nomes das colunas originais
pca_componentes = pd.DataFrame(reducao.components_, columns=colunas_originais)

# Visualizar as contribuições das colunas originais em cada um dos 10 componentes principais
print(pca_componentes)

         0         1         2         3         4         5         6   \
0  0.005086  0.002197  0.035076  0.516826  0.000041  0.000082  0.000048   
1  0.009287 -0.002882  0.062748  0.851824 -0.000003  0.000075  0.000046   
2 -0.012343 -0.006365 -0.071671 -0.027893  0.000102  0.000266  0.000036   
3  0.034326  0.361537  0.330039 -0.039524  0.003011  0.003412  0.001249   
4 -0.035377  0.444720 -0.312658  0.045953 -0.002521 -0.002189 -0.001130   
5  0.131221  0.214776  0.840038 -0.052328  0.001005 -0.000292  0.000568   
6 -0.034233  0.783234 -0.190094  0.007367 -0.000183 -0.000882 -0.000839   
7 -0.098465 -0.107340  0.118356 -0.003855  0.020814  0.023759  0.011171   
8  0.353198 -0.001443 -0.135855  0.003924 -0.056796 -0.070608 -0.019453   
9 -0.443353  0.017688  0.017083  0.003122  0.119994  0.183018  0.057166   

         7         8         9         10        11        12        13  \
0  0.000314  0.002236  0.055727  0.000003  0.007155  0.003067  0.049458   
1 -0.000054  0.000820  0

Os testes nessa abordagem foram feitos a partir de previsores com dimensionalidade reduzida
- 1 teste com valores randômicos
- 2 testes com valores reais de 'previsores_decompose' correspondentes ao dataset original

In [336]:
# Dados que usaremos para teste
data_search = (data['id'] == 8510653) | (data['id'] == 866458)
data[data_search]

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
20   8510653         B        13.08         15.71           85.63      520.0   
128   866458         B        15.10         16.39           99.58      674.5   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
20            0.1075            0.1270         0.04568              0.03110   
128           0.1150            0.1807         0.11380              0.08534   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
20   ...          20.49            96.09       630.5            0.1312   
128  ...          18.33           105.90       762.6            0.1386   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
20              0.2776            0.189               0.07283          0.3184   
128             0.2883            0.196               0.14230          0.2590   

     fractal_dimension_worst  Unnamed: 32  
20                   0.08183          NaN  
128                  0.07779          NaN  

[2 rows x 33 columns]

In [335]:
# Teste1 (valores Randômicos)
paciente1 = [
    1523.7843, -283.4521, -13.7289, -5.2347, -1.2438, -1.6784, 1.2543, 0.2381, -0.2875, -0.3956
]
paciente1 = np.asarray(paciente1).reshape(1,-1)

# Teste2 (valores de previsores_decompose) - linha 20 / id: 849014 / diagnostico esperado: M
paciente2 = [
    1615.09344319643,-270.33333280241885,-15.542798505507696,-4.88303901133456,-1.0611308487520503,-1.5317850581189276,1.3123352855998005,0.19167812082566424,-0.3099736883164397,-0.3731023813569888
]
paciente2 = np.asarray(paciente2).reshape(1,-1)

# Teste2 (valores de previsores_decompose) - linha 130 / id: 866458 / diagnostico esperado: B
paciente3 = [
    -90.2469797899298,78.61448403396977,3.4180728853477937,0.3564504256239758,-8.678752764820509,3.973514229683676,0.5314623122731341,-0.07672504616998364,-0.20085516418299007,-0.034734854486045845
]
paciente3 = np.asarray(paciente3).reshape(1,-1)

In [337]:
xgb.fit(previsores_decompose_deploy,alvo_deploy)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, random_state=0, ...)

In [338]:
resultado1 = xgb.predict(paciente1)

diagnostico(resultado1)

Câncer está com diagnostico Maligno


In [339]:
resultado2 = xgb.predict(paciente2)

diagnostico(resultado1)

Câncer está com diagnostico Maligno


In [340]:
resultado3 = xgb.predict(paciente3)

diagnostico(resultado3)

Câncer está com diagnostico Benigno
